title: Lam Ying Xian # your name (or website title) here
logo: "images/Portrait Photo.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An aspiring data scientist who is result-oriented, self-starter, data-driven, innovative problem-solver, resilient and avid learner.
  <a href="https://www.linkedin.com/in/lam-ying-xian-蓝颖娴-4556b5b5/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://public.tableau.com/app/profile/lam.ying.xian">View My Tableau Profile</a> 
  <br><br>
  <a href="https://github.com/lam771994">View My GitHub Profile</a> 
  <br><br>
  <br><br>
  
  



